//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PBXClient.rc
//
#define IDAPPLY                         3
#define IDD_DIALINGRULESSETTINGSDLG     104
#define IDR_MAINFRAME                   128
#define IDR_PBXCLITYPE                  129
#define IDD_DIALOG_SETTINGS             130
#define IDD_OUTLOOKCONTACTS_DIALOG      132
#define IDB_BITMAP1                     134
#define IDB_SKIN_MSN                    135
#define IDB_POPUP                       135
#define IDI_ICON_DISCONNECTED           137
#define IDI_ICON_CONNECTED              138
#define IDI_ICON_CONNECTING1            139
#define IDI_ICON_CONNECTING2            140
#define IDI_ICON_RED                    142
#define IDD_DIALOG_DEBUG                143
#define IDD_DIALOG_ADD_EXTENSION        150
#define IDD_DIALOG_MISSED_CALLS         151
#define IDD_DIALOG_LOADING_CONTACTS     152
#define IDD_DIALOG_FIND_CONTACT         162
#define IDD_DIALOG_ACTIVE_CALLS         163
#define IDD_DIALOG_SETTINGS_SERVER      170
#define IDD_DIALOG_SETTINGS_OUTLOOK     171
#define IDD_DIALOG_SETTINGS_EXTENSIONS  172
#define IDD_DIALOG_SETTINGS_GENERAL     173
#define IDB_BITMAP_OUTCALL              174
#define IDB_BITMAP2                     176
#define IDD_DIALOG_ADD_LANGUAGE         177
#define IDD_DIALOG_SETTINGS_DIALING_RULES 180
#define IDD_DIALOG_MAP_CONTACT_FIELDS   181
#define IDD_DIALOG_SETTINGS_IMPORT_RULES 182
#define IDD_DIALOG_OUTLOOK_RULE         183
#define IDC_BUTTON_CHECK_UPDATES        1000
#define IDC_CHECK_AUTOMATIC_START       1001
#define IDC_BUTTON_INSTALL_UPDATES      1001
#define IDC_EDIT_SERVER                 1002
#define IDC_STATIC_PICTURE3             1002
#define IDC_EDIT_USERNAME               1003
#define IDC_STATIC_PICTURE1             1003
#define IDC_EDIT_PASSWORD               1004
#define IDC_STATIC_PICTURE2             1004
#define IDC_EDIT_NUMBER                 1005
#define IDC_STATIC_STATUS1              1005
#define IDC_COMBO_PROTOCOL              1006
#define IDC_STATIC_STATUS2              1006
#define IDC_EDIT_PORT                   1007
#define IDC_STATIC_STATUS3              1007
#define IDC_CHECK_AUTOMATIC_CONNECT     1008
#define IDC_STATIC_STATUS4              1008
#define IDC_EDIT_DELAY_TIME             1009
#define IDC_STATIC_STATUS5              1009
#define IDC_CONTACT                     1010
#define IDC_STATIC_STATUS6              1010
#define IDC_PHONE                       1011
#define IDC_STATIC_LICENCE              1012
#define IDC_STATIC_NAME                 1016
#define IDC_STATIC_COMPANY              1017
#define IDC_CHECK_SHOW_AT_STARTUP       1018
#define IDC_CHECK_NEW_CONTACT_WINDOW    1019
#define IDC_EDIT_DEBUG_INFO             1020
#define IDC_BUTTON_CLEAR                1021
#define IDC_EDIT_NAME                   1023
#define IDC_EDIT_COMPANY                1024
#define IDC_BUTTON_REGISTER             1025
#define IDC_SEPARATOR                   1026
#define IDC_SEPARATOR2                  1027
#define IDC_EDIT_SERIAL                 1028
#define IDC_STATIC_STATUS               1029
#define IDC_STATIC_SENDING_REQUEST      1030
#define IDC_STATIC_REGISTERING          1031
#define IDC_PICTURE1                    1032
#define IDC_PICTURE2                    1033
#define IDC_CHECK_SEARCH_O_CONTACTS     1033
#define IDC_STATIC_SENDING_REQUEST2     1034
#define IDC_CHECK_O_INTEGRATION         1034
#define IDC_STATIC_REGISTERING2         1035
#define IDC_STATIC_SEPARATOR            1036
#define IDC_CHECK_ENABLE_O_FEATURES     1037
#define IDC_LIST                        1039
#define IDC_BUTTON_ADD                  1040
#define IDC_BUTTON_REMOVE               1041
#define IDC_EDIT_EXTENSION              1041
#define IDC_BUTTON_EDIT                 1042
#define IDC_COMBO_DIAL_FROM             1043
#define IDC_EDIT_PASSWORD2              1043
#define IDC_STATIC_SEPARATOR2           1044
#define IDC_COMBO_PHONE                 1047
#define IDC_COMBO_DATE                  1048
#define IDC_COMBO_SHOW                  1049
#define IDC_BUTTON_CALL                 1050
#define IDC_BUTTON_SKIP                 1051
#define IDC_BUTTON_ADD_CONTACT          1051
#define IDC_STATIC_SN                   1053
#define IDC_STATIC_VERSION              1054
#define IDC_PROGRESS1                   1055
#define IDC_CHECK_REFRESH_CONTACTS      1056
#define IDC_EDIT_REFRESH_INTERVAL       1057
#define IDC_BUTTON_OPTIONS              1059
#define IDC_RADIO_FIRSTLAST             1060
#define IDC_BUTTON_REFRESH2             1060
#define IDC_BUTTON_SORT                 1060
#define IDC_BUTTON_FIND                 1060
#define IDC_RADIO_LASTFIRST             1061
#define IDC_BUTTON_SORT_ITEMS           1067
#define IDC_STATIC_FRAME                1068
#define IDC_CHECK_IGNORE_CALLS          1069
#define IDC_COMBO_MIN_DIGITS            1071
#define IDC_EDIT_UPDATES                1072
#define IDC_EDIT_SOURCE                 1073
#define IDC_EDIT_DEST                   1074
#define IDC_STATIC_NUMBER_CONTACTS      1074
#define IDC_EDIT_CONNECTIONS            1075
#define IDC_CHECK_NN_CALLERID           1075
#define IDC_EDIT1                       1076
#define IDC_EDIT_SEARCH                 1076
#define IDC_EDIT_OUTGOING_CONTEXT       1076
#define IDC_EDIT_PREFIX                 1076
#define IDC_CHECK1                      1077
#define IDC_RADIO1                      1078
#define IDC_RADIO2                      1079
#define IDC_RADIO3                      1080
#define IDC_BUTTON_DIAL                 1082
#define IDC_LIST_RESULTS                1083
#define IDC_COMBO1                      1084
#define IDC_CHECK_FILTER_CONTACTS       1087
#define IDC_LIST1                       1088
#define IDC_BUTTON_HANGUP               1089
#define IDC_EDIT_PHONE_NUMBER           1091
#define IDC_STATIC_LINK_BS              1092
#define IDC_TAB                         1095
#define IDC_STATIC_PICTURE              1096
#define IDC_STATIC_BS_LINK              1097
#define IDC_STATIC_PHONE_NUMBERS        1100
#define IDC_STATIC_POWERED_BY           1101
#define IDC_STATIC_GROUP                1102
#define IDC_STATIC_OUT_CONTEXT          1103
#define IDC_STATIC_POPUP_DELAY          1104
#define IDC_STATIC_OUTLOOK_SETTINGS     1105
#define IDC_STATIC_CONTACT_DETAILS      1106
#define IDC_STATIC_SERVER               1107
#define IDC_STATIC_USERNAME             1108
#define IDC_STATIC_PASSWORD             1109
#define IDC_STATIC_PORT                 1110
#define IDC_STATIC_ACTIVE_CALLS         1111
#define IDC_STATIC_EXTENSION            1112
#define IDC_STATIC_PROTOCOL             1113
#define IDC_STATIC_PASSWORD2            1114
#define IDC_STATIC_DEBUG_INFO           1115
#define IDC_STATIC_DIAL_FROM            1116
#define IDC_STATIC_SEARCH               1117
#define IDC_STATIC_PHONE                1118
#define IDC_STATIC_PLEASE_WAIT          1119
#define IDC_STATIC_FILTER               1120
#define IDC_STATIC_SHOW                 1121
#define IDC_STATIC_DATE                 1122
#define IDC_STATIC_CONTACT              1123
#define IDC_STATIC_LANGUAGE             1124
#define IDC_COMBO_LANGUAGE              1125
#define IDC_STATIC_SELECT_LANGUAGE      1126
#define IDC_BUTTON_ADD_LANGUAGE         1127
#define IDC_LIST_LANGUAGES              1128
#define IDC_STATIC_FRAME_LANGUAGE       1129
#define IDC_EDIT_OUTGOING_PREFIX        1130
#define IDC_EDIT_STRIP_OPTIONS          1131
#define IDC_STATIC_OUTGOING_PREFIX      1132
#define IDC_STATIC_STRIP                1133
#define IDC_LIST_OUTLOOK_FIELDS         1134
#define IDC_BUTTON_MAP_FIELDS           1135
#define IDC_STATIC_OUTCALL_FIELDS       1136
#define IDC_STATIC_OUTLOOK_FIELDS       1137
#define IDC_COMBO_MAIL_PROFILE          1138
#define IDC_BUTTON_UPDATE_DATABASE      1138
#define IDC_STATIC_MAIL_PROFILE         1139
#define IDC_EDIT_REPLACEMENT            1139
#define IDC_STATIC_CHOOSE_MAIL_PROFILE  1140
#define IDC_STATIC_PREFIX               1140
#define IDC_STATIC_REPLACEMENT          1141
#define IDC_STATIC_DESCRIPTION          1143
#define ID_FILE_ABOUT                   32772
#define ID_FILE_CONNECT                 32773
#define ID_FILE_CALL                    32774
#define ID_FILE_HELP                    32775
#define ID_FILE_ADDCONTACT              32777
#define ID_FILE_ASTERISKDEBUGINFO       32778
#define ID_FILE_REGISTER                32779
#define ID_FILE_MISSEDCALLS             32780
#define ID_FILE_UPDATEOUTCALL           32781
#define ID_POPUP_REFRESH                32782
#define ID_POPUP_ORDER                  32783
#define ID_DISPLAY_FIRSTNAME            32784
#define ID_DISPLAY_LASTNAME             32785
#define ID_GFGSFDGFD_FDSFDGDFGDSF       32786
#define ID_FILE_REFRESHCONTACTS         32787
#define ID_FINDPOPUP_BYNAME             32788
#define ID_FINDPOPUP_BASURNAME          32789
#define ID_FINDPOPUP_BYCOMPANY          32790
#define ID_POPUP_HIDECONTACTSWITHNOTELEPHONENUMBERS 32791
#define ID_FILE_ACTIVECALLS             32792
#define ID_FILE_FIND                    32793
#define ID_HELP_ONLINEHELP              32794
#define ID_HELP_EBOOK                   32795
#define ID_FILE_HELP32797               32797
#define ID_FILE_ONLINEHTML              32799
#define ID_HELP_CONTACTSUPPORT          32800
#define ID_HELP_ONLINEPDF               32801
#define ID_FILE_SETTINGS                32802
#define ID_REFRESHCONTACTS_IMPORTFROMCSVFILE 32804
#define ID_IMPORTCONTACTS_FROMOUTLOOK   32805
#define ID_IMPORTCONTACTS_FROMCSVFILE   32806
#define ID_REFRESHCONTACTS_IMPORTFROMOUTLOOK 32807

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1144
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
